WonderTix/WonderTix

client/src/components/CRM/Accounts/Accounts.tsx, client/src/components/CRM/Contacts/ContactResults.tsx, client/src/components/CRM/Contacts/Contacts.tsx, client/src/components/CRM/Reporting/Reporting.tsx, client/src/components/CRM/Reporting/SavedPanel.tsx, client/src/components/Ticketing/userdashboard/Add_event/addevent.tsx, server/src/api/events/event.router.ts
Updated the URLs in the API calls from the client to use the new updated routes. The reporting API calls all need to be completely reworked, which will happen later when we rewrite the reporting stuff.
Issue #48 
N/A
I tested all the functionality from the client side that made these API calls, except for the reporting ones, because that is currently not working. 
* Operating System: N/A used docker
* Node Version: N/A used docker
* NPM Version: N/A used docker
I just changed URLs in existing API calls, no real major additions made. I did verify that the URLs are correct.
=> Fixed API calls

server/jest.config.js, server/package-lock.json, server/package.json, server/src/api/accounts/accounts.router.test.ts, server/src/api/contacts/contacts.router.test.ts, server/src/api/donations/donations.router.test.ts, server/src/api/doorlist/doorlist.router.test.ts, server/src/api/task_notes/task_notes.router.test.ts, server/src/api/task_notes/task_notes.router.ts
Added router testing for the following routers: accounts, contacts, donations, doorlist
Tests use Jest / Supertest to mock the service functions and provide the appropriate status code to the router
Required NPM installs:
npm install --save-dev supertest 
npm install --save @types/supertest
npm install --save-dev jest
npm install --save @types/jest
Issue #
None
* Operating System: Windows 10
* Node Version: 16.16.0
* NPM Version: 8.11.0
=> Router testing setup

client/src/components/Ticketing/checkout/CheckoutPage.tsx, client/src/components/Ticketing/donation/OnlyDonatePage.tsx, docker-compose.yml, server/jest.config.js, server/package-lock.json, server/package.json, server/src/api/accounts/accounts.router.test.ts, server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.test.ts, server/src/api/contacts/contacts.router.ts, server/src/api/donations/donations.router.test.ts, server/src/api/donations/donations.router.ts, server/src/api/doorlist/doorlist.router.test.ts, server/src/api/doorlist/doorlist.router.ts, server/src/api/events/event.router.ts, server/src/api/newsletter/newsletter.router.ts, server/src/api/subscriptions/subscription.router.ts, server/src/api/task_notes/task_notes.router.test.ts, server/src/api/task_notes/task_notes.router.ts, server/src/api/tasks/tasks.router.ts, server/src/api/tickets/ticket.router.ts, server/src/auth.ts, server/src/server.ts, server/src/testSetup.ts
Added https and Auth0 to backend, setup protected routes. Also fixed all existing tests to use authentication. Specifically, added setupTests to run before each test file, which authenticates with the auth0 API and gets a token to use in tests.
Issue #67 
N/A
...
* NPM Version:
=> Backend auth

client/src/components/Ticketing/checkout/CompleteOrderForm.tsx, server/src/api/events/event.router.ts, server/src/api/orders/order.service.ts
Decrements event_instances.availableseats on purchase of tickets.  Also fixed boolean checkboxes on checkout page.
Purchasing tickets does not reduce available tickets for an event instance[#81](https://github.com/WonderTix/WonderTix/issues/81)
Nothing I can see.
...
* NPM Version:
Minor bug fixes.  Very little change in code.
Changes to checkout post stripe process. Stripe needs a webhook to complete purchases.
=> Availableseats

client/package-lock.json, client/src/components/Ticketing/mainpage/Seasonalt.test.tsx, client/src/components/Ticketing/mainpage/footer.test.tsx, client/src/components/Ticketing/mainpage/hero.test.tsx, client/yarn.lock
-Added unit tests for Main Page: hero.tsx, footer.tsx, Seasonalt.tsx
Dependencies added: 
-- npm install --save-dev jest
-- npm i @testing-library/jest-dom
-- npm i @testing-library/react@12.1.2
-- npm i @testing-library/user-event
Issue #
None
* Operating System: macOS Monterrey
* Node Version: v18.5.0
* NPM Version: 8.12.1
=> Unittest mainpage

server/src/api/db.ts, server/src/api/doorlist/doorlist.router.test.ts, server/src/api/doorlist/doorlist.router.ts, server/src/api/doorlist/doorlist.service.ts, server/src/api/newsletter/newletter.service.ts, server/src/api/newsletter/newsletter.router.ts, server/src/api/subscriptions/subscription.router.ts
=> Gary documentation

server/package-lock.json, server/package.json, server/src/api/accounts/accounts.router.ts, server/src/api/authentication/readme.md, server/src/api/contacts/contacts.router.ts, server/src/api/donations/donations.router.ts, server/src/api/events/event.router.ts, server/src/api/events/event.service.ts, server/src/api/orders/order.router.ts, server/src/schema/accounts.yaml, server/src/schema/contacts.yaml, server/src/schema/donations.yaml, server/src/schema/doorlist.yaml, server/src/schema/responses.yaml, server/src/schema/test.yaml, server/src/schema/v1.yaml, server/src/server.ts, terraform/create_cert.tf, terraform/locals.tf, terraform/modules/cloudfront/main.tf, terraform/modules/cloudfront/variables.tf, terraform/modules/route53/main.tf, terraform/modules/route53/variables.tf, terraform/modules/s3/main.tf, terraform/modules/s3/variables.tf, terraform/providers.tf, terraform/route53.tf, terraform/variables.tf
Added swagger documentation to some API routes
Issue #
N/A
N/A, only added documentation
Only added documentation, no code changes
N/A
=> Swagger docs

client/src/interfaces/popup.interface.ts, client/src/interfaces/showing.interface.ts, server/src/auth.ts, server/src/interfaces/CartItem.ts, server/src/interfaces/Event.ts, server/src/interfaces/LoadStatus.ts, server/src/interfaces/Showing.ts, server/src/interfaces/Ticket.ts, server/src/interfaces/TicketingState.ts, server/src/interfaces/TicketsState.ts, server/src/interfaces/User.ts, server/src/server.ts
Documentation
Issue #
...
* NPM Version:
=> Added Documentation for Intefaces, Auth and Server implementation

client/src/components/Ticketing/cart/Cart.tsx, client/src/components/Ticketing/cart/CartItem.tsx, client/src/components/Ticketing/cart/YourOrder.tsx, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/ticketing/ticketingSlice.ts, postgres/wtix_db.sql, server/src/api/tickets/ticket.router.ts, server/src/api/tickets/ticket.service.ts, server/src/interfaces/Ticket.ts, sql-scripts/create_tables.sql, task_sql/wtix_dump_030422.sql
- Added routes to add and delete ticket types 
Issue #
Tested routes using Postman
* Operating System: macOS Monterey
* Node Version: v18.5.0
* NPM Version: 8.12.1
Still need to write unit test, running into issues with jest.  Tested both routes on Postman and both work.
=> Post delete ticket types

server/package-lock.json, server/package.json, server/src/api/accounts/accounts.router.ts, server/src/api/authentication/readme.md, server/src/api/contacts/contacts.router.ts, server/src/api/donations/donations.router.ts, server/src/api/events/event.router.ts, server/src/api/events/event.service.ts, server/src/api/orders/order.router.ts, server/src/schema/accounts.yaml, server/src/schema/contacts.yaml, server/src/schema/donations.yaml, server/src/schema/doorlist.yaml, server/src/schema/responses.yaml, server/src/schema/test.yaml, server/src/schema/v1.yaml, server/src/server.ts, terraform/create_cert.tf, terraform/locals.tf, terraform/modules/cloudfront/main.tf, terraform/modules/cloudfront/variables.tf, terraform/modules/route53/main.tf, terraform/modules/route53/variables.tf, terraform/modules/s3/main.tf, terraform/modules/s3/variables.tf, terraform/providers.tf, terraform/route53.tf, terraform/variables.tf
Reverts WonderTix/WonderTix#108
Verified issues to be local and have documented them for future troubleshooting. Resolved dependencies not being found by deleting and recreating docker images.
=> Revert "Revert "Swagger docs""

server/src/api/accounts/accounts.router.ts, server/src/api/accounts/accounts.service.ts, server/src/api/contacts/contacts.router.ts, server/src/api/contacts/contacts.service.ts, server/src/api/discounts/discounts.router.ts, server/src/api/discounts/discounts.service.ts, server/src/api/donations/donations.service.ts, server/src/api/doorlist/doorlist.service.ts, server/src/api/orders/order.service.ts, server/src/api/subscriptions/subscription.router.ts, server/src/api/task_notes/task_notes.service.ts
Refactored the queries for:
-Accounts
-Countacts
-Donations
-Task Notes
-Subscriptions
-Doorlist
- [ *] Major change (potentially breaking, list anything that is broken below)
...
- [ *] Docker was used.
* Operating System: Win 10
* Node Version: 16.16.0
* NPM Version: 8.18.0
- [ *] My code follows the styling guidelines.
- [ *] I have added unit tests and verified that they pass.
- [ *] I have used the linter and fixed any linting issues.
- [ *] I have commented the code.
- [ *] I have adjusted the documentation to match the changed code.
- [ *] Prior to submitting the PR, I made sure the latest changes were merged with my branch.
- [ *] Existing tests pass locally with changes.
=> Refactored queries

client/.eslintrc.json
Added linting rule to turn off warnings for different line breaks. See [https://eslint.org/docs/latest/rules/linebreak-style](https://eslint.org/docs/latest/rules/linebreak-style)
Issue #
...
* NPM Version:
=> add linting rule for linebreaks

client/.eslintrc.json, client/package-lock.json, client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/Events/Add_event/CreateEventPage.tsx, client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx, client/src/components/Ticketing/ticketingmanager/Events/showListController.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, client/yarn.lock, server/src/api/events/event.service.ts, server/src/interfaces/Showing.ts
Reverts WonderTix/WonderTix#140
=> Revert "Final Routefix and Input Fix"

client/.eslintrc.json, client/package-lock.json, client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/Events/Add_event/CreateEventPage.tsx, client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx, client/src/components/Ticketing/ticketingmanager/Events/showListController.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, client/yarn.lock, server/src/api/events/event.service.ts, server/src/interfaces/Showing.ts
Reverts WonderTix/WonderTix#141 Revert of the Revert
=> Revert "Revert "Final Routefix and Input Fix""

client/src/components/Ticketing/ticketingmanager/ticketing/ticketingSlice.spec.ts, client/src/components/Ticketing/ticketingmanager/ticketing/ticketingSlice.ts
Updated `TicketState` in `ticketingSlice.ts` to handle new response from the server. 
Issue #
...
* Operating System: win10
* NPM Version:
=> Update TicketState to handle response from server

client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx
Changes to variables due to DB changes
Issue #
...
* Operating System: macOs Ventura 13.0
* Node Version: v18.5.0
* NPM Version: 8.12.1
=>  Changes to variables due to DB changes

server/src/api/events/event.service.ts
-Events created through UI now show up on the Main page, Simple query change
Issue #
...
* Operating System: macOS Ventura 13.0
* Node Version: v18.5.0
* NPM Version: 8.12.1
=> Events created through UI now show up on Main page

client/src/components/Ticketing/cart/Cart.tsx
Refactored applyDiscount function (which handles discount code search) to avoid briefly flashing the "invalid discount code" message even when the code was good. Also moved the message to above the discount code button instead of below, to avoid moving UI elements around.
No changes to functionality.
Nothing.
Several codes, both valid and invalid, were tried. No erroneous behavior noted.
* Operating System: Win10
* Node Version: v14.16.1
* NPM Version: v6.14.12
No new unit tests needed.
None
=> Further discount code tweaks

server/src/api/accounts/accounts.router.ts
Issue #
...
* NPM Version:
There are no unit tests used to check the doc-blocks that will anotate the Swagger documentation. 
This PR will only cover the documentation for the account class, there will be multiple PR's that will cover the …
=> swagger doc blocks for accounts

server/src/api/doorlist/doorlist.router.ts
=> swagger docs for doorlist

server/src/api/tasks/tasks.router.ts, server/src/api/tasks/tasks.service.ts
swagger docs for tasks routes.
Also fixing a small bug in the service that is using a incorrect column name.
=> Swagger docs tasks

server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.ts
Issue #
...
* NPM Version:
They don't apply for change made. 
Working through: https://localhost:8000/api/docs
=> Swagger doc block contacts

server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.ts, server/src/api/discounts/discounts.router.ts
Issue #
...
* NPM Version:
The unchecked don't apply to my PR.
Run on: https://localhost:8000/api/docs/
=> Swagger doc block discounts

server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.ts, server/src/api/discounts/discounts.router.ts, server/src/api/donations/donations.router.ts
Issue #
...
* NPM Version:
- [] Existing tests pass locally with changes.
Unchecked don't apply to the PR.
Run: https://localhost:8000/api/docs/
=> Swagger doc block donations

server/src/api/orders/order.router.ts
Added basic doc for the orders webhook route
=> swagger docs for order webhook

server/src/api/reporting/reporting.router.ts
swagger docs for reporting routes
=> swagger docs for reporting routes

server/src/api/refunds/refunds.router.ts
add swagger docs for refunds route.
Note this route does not work correctly
=> swagger docs for refunds

server/src/api/subscriptions/subscription.router.ts
=> swagger docs for subscriptions

server/src/api/newsletter/newsletter.router.ts
swagger docs for newsletter routes
=> swagger docs for newsletter routes

server/src/api/tickets/ticket.router.ts
Swagger docs for ticket router
=> swagger docs for ticket types

server/src/api/saved_reports/saved_reports.router.ts, server/src/api/saved_reports/saved_reports.service.ts
Swagger docs for saved reports.
Fixing wrong table name in saved report routes.
=> Swagger docs saved reports

server/src/api/task_notes/task_notes.router.ts
swagger docs for task notes routes
=> swagger docs for task notes

server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.ts, server/src/api/discounts/discounts.router.ts, server/src/api/donations/donations.router.ts, server/src/api/doorlist/doorlist.router.ts, server/src/api/newsletter/newsletter.router.ts, server/src/api/orders/order.router.ts, server/src/api/refunds/refunds.router.ts, server/src/api/reporting/reporting.router.ts, server/src/api/subscriptions/subscription.router.ts, server/src/api/tasks/tasks.router.ts, server/src/server.ts
tiny bit cleanup adding tags to routes and a few white space lint fixes
=> Swagger doc route cleanup

server/Dockerfile, server/src/server.ts
Removed creation of cert for server.
You will need to make the cert on the host machine like before.
=> revert auto install of cert

server/src/api/events/event.router.ts
adding Swagger doc blocks for event annotations.
Issue #
...
* NPM Version:
Documentation code doesn't require testing. 
Test on https://localhost:8000/api/docs
=> swagger doc blocks: event 

server/src/api/events/event.router.ts
Some of the event routes didn't have the correct url.
There was a few minor white spacing issues as well.
=> update events url in swagger docs

README.md, client/src/components/Ticketing/checkout/CheckoutPage.tsx
Changed public stripe key for checkout from a hardcoded key to a .env variable. 
Issue #
...
* NPM Version:
=> Stripe public key client update 

client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/event/eventshowings.tsx, client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx
- Added the ticket type option to the events page 
- Changed on submit modal text
Issue #142 
=> Ticket type option

server/src/api/doorlist/doorlist.router.ts
added eventinstance to the query param
Adding the eventinstance integer as a parameter to the doorlist endpoint 
Issue #
...
* NPM Version:
=> Adding parameters for doorlist

server/package.json, server/prisma/migrations/20230524160200_init/migration.sql
fixes issues with conflicting ids
None
Manaual
Not relevent
=> Prisma serial fields

server/src/api/accounts/accounts.router.ts, server/src/api/contacts/contacts.router.ts, server/src/api/discounts/discounts.router.ts, server/src/api/donations/donations.router.ts, server/src/api/doorlist/doorlist.router.ts, server/src/api/events/event.router.ts, server/src/api/newsletter/newsletter.router.ts, server/src/api/orders/order.router.ts, server/src/api/refunds/refunds.router.ts, server/src/api/reporting/reporting.router.ts, server/src/api/saved_reports/saved_reports.router.ts, server/src/api/subscriptions/subscription.router.ts, server/src/api/task_notes/task_notes.router.ts, server/src/api/tasks/tasks.router.ts, server/src/api/ticket_types/ticket_types.router.ts, server/src/api/tickets/ticket.router.ts, server/src/controllers/contactController.ts, server/src/server.ts
adds new contacts route for api 2
None
Use swagger to test the routes
* NPM Version:
Swagger library does not support two separate swagger docs so they are all included in one swagger doc
=> Api 2 contacts routes

client/src/components/CRM/Dashboard.tsx, client/src/components/Ticketing/mainpage/eventcard.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, client/src/components/Ticketing/ticketingmanager/dashboard.tsx
I made showings in event management look nicer, and fixed a sizing bug for the events on the main page. 
Issue #
...
* NPM Version:
=> Updated styles for ShowingInputContainer and ListComponent

.github/workflows/run-tests.yml, client/package.json, server/package.json
Removes deployments to production from GitHub actions so that there aren't unnecessary comments in PRs anymore. 
Nothing was actually getting deployed to any kind of production environment. Updated server/client `package.json` to include node and npm versions.
Builds and runs locally
none
win10
=> Update actions and node/npm versions

.env.dist, server/src/auth.js, server/src/auth.ts
*Brief description of changes*
*Potential areas of concern that you would like looked at more closely*
*How you verified that these changes work*
*Link to corresponding issue*
*If you're on Mac, please include whether you are on an Intel or M-series CPU*
=> Donor management

README.md
=> [DEP-12] readme updated

README.md
Just merging README changes from `main` into `ticketing`
None
N/a
N/a
N/a
=> [TIC] Update Ticketing with latest from Main

README.md, docker-compose.yml
Added new environment variable for accessing the Prisma base URL. And minor README tweaks.
None
N/A
[*TIC-20*](https://pdx-hkaus.atlassian.net/browse/TIC-20)
Windows 11
=> TIC-20: prep for Prisma conversions

server/src/api/donations/donations.router.test.ts, server/src/api/donations/donations.router.ts, server/src/api/donations/donations.service.ts
Refactored donation endpoint names & updated jest tests, to better match naming patterns and provide clarity.
Old Method -> Renamed Method
find( id ) -> findById(id)          
Added new endpoint:
findByDonationDate(date)
None
Swagger UI
Code Clarity
Windows 11
=> Refactored donation endpoint names & added endpoint to search donors by donation dates

client/package.json
fixed deleted code from rebase error in [[DEP-22] mkcert fixed #297](https://github.com/WonderTix/WonderTix/pull/298/files#top)
#298
regarding changes introduced in [Update actions and node/npm versions (](https://github.com/WonderTix/WonderTix/commit/d99b507dbe60e9fcf5903f649f59af4ad2f55033)https://github.com/WonderTix/WonderTix/pull/282[)](https://github.com/WonderTix/WonderTix/commit/d99b507dbe60e9fcf5903f649f59af4ad2f55033)
=> fix deleted code

client/src/App.tsx, client/src/components/DonorManagement/Dashboard.tsx
Description:
Added new routing to Donor Management Dashboard page:
> localhost:3000/admin/donor
=> Don donor dashboard branch

client/src/components/CRM/Accounts/ManageUsers/ManageAccounts.tsx, client/src/components/CRM/Accounts/SearchAccount/Accounts.tsx, client/src/components/CRM/Contacts/ContactOneResult.tsx, client/src/components/CRM/Contacts/ContactResults.tsx, client/src/components/CRM/Contacts/Contacts.tsx, client/src/components/CRM/Reporting/AccountsPanel.tsx, client/src/components/CRM/Reporting/ContactsPanel.tsx, client/src/components/CRM/Reporting/DonationsPanel.tsx, client/src/components/CRM/Reporting/Reporting.tsx, client/src/components/CRM/Reporting/SavedPanel.tsx, client/src/components/CRM/Tasks/Search.tsx, client/src/components/Ticketing/mainpage/Navbar.tsx, client/src/components/Ticketing/ticketingmanager/Doorlistpage/doorlist.tsx, client/src/components/Ticketing/ticketingmanager/Events/Add_event/CreateEventPage.tsx, client/src/components/Ticketing/ticketingmanager/Events/Add_event/addevent.tsx, client/src/components/Ticketing/ticketingmanager/Events/Delete_event/Deleteevent.tsx, client/src/components/Ticketing/ticketingmanager/Events/Edit_event/EditEventPage.tsx, client/src/components/Ticketing/ticketingmanager/TicketTypes/tickettypes.tsx, client/src/components/Ticketing/ticketingmanager/showings/showing/showing.tsx, client/src/utils/arrays.tsx, docker-compose.yml, server/src/api/orders/order.router.ts, server/src/auth.js, server/src/server.js, server/src/server.ts
Replaces all hard-coded values that should be environment variables and added an env var to the server for the base url. All the hard-coded values replaced were for the auth0 integration. 
New env variables should be getting configured properly after composing up
Tested with multiple different Auth0 applications, passes unit tests
[https://github.com/orgs/WonderTix/projects/3/views/1?pane=issue&itemId=35176383](https://github.com/orgs/WonderTix/projects/3/views/1?pane=issue&itemId=35176383)
win10
=> Replace hard-coded values with environment variables

client/src/components/Ticketing/mainpage/PageNotFound.tsx
Added bMode prop to Navbar in 404 page component
NA
Tested all links on 404 page. 
[*Link to corresponding ticket*
](https://pdx-hkaus.atlassian.net/browse/TIC-50)
M1 Mac
=> [TIC-50] Fixed functionality of 404 page Navbar 

client/src/components/CRM/Accounts/AccountsDash.tsx, client/src/components/CRM/Accounts/AccountsMain.tsx, client/src/components/CRM/Dashboard.tsx, client/src/components/Ticketing/ticketingmanager/dashboard.tsx, client/src/components/Ticketing/userdashboard/DashboardLink.tsx
Visually, the only difference is that a pointer now appears for the cursor when hovering admin/ticketing/account dashboard button elements.
Included in this work was...
1. Turning `<a>` elements into `<button>` elements for the functionality. The rational is that `href` wasn't being used but `onClick` was.
2. Refactored the Dashboard Links to be their own reusable components. Made the appropriate conversions.
Possibly merge conflicts with other users working in similar files.
Manually clicked every button to ensure that it still routed. Compared with older WonderTix version in deployment.
[TIC-54](https://pdx-hkaus.atlassian.net/browse/TIC-54)
Windows 11
[TIC-54]: https://pdx-hkaus.atlassian.net/browse/TIC-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> [TIC-54] Pointer appears when hovering dashboard buttons

client/Dockerfile, client/package-lock.json, client/package.json
Removed conflicting dependencies which required `npm i --force` in the `client` directory.
If flowbite happens to have been used (although I think I checked everywhere), then the pages it is on will likely not work. But I don't believe it is the case. If it does happen, then this PR is easy to revert.
Checked for any uses of `flowbite` or `flowbite-react`.
N/A
Windows 11
=> Remove flowbite dependencies

client/src/App.tsx, client/src/components/DonorManagement/Dashboard.tsx, client/src/components/DonorManagement/DmDashmain.tsx, client/src/components/DonorManagement/Navigation.tsx, client/src/components/DonorManagement/Reporting/DonorReporting.tsx
**Description:**
This pull request aims to introduce the Donors Dashboard feature by adding the initial frontend components and establishing routing for seamless navigation. The key changes encompassed in this update are as follows:
**Files Added/Modified:**
- Donormanagement/Dashboard.tsx
- Donormanagement/DmDashmain.tsx
- Donormanagement/Navigation.tsx
- Donormanagement/Reporting/DonorReporting.tsx
Modified: App.tsx (Added a new route for the Donors Reports page)
**Changes Made:**
Donor Management Directory:
Introduced the DmDashmain.tsx file to serve as the main dashboard container.
Created the Dashboard.tsx file to provide the primary content of the dashboard.
Designed the Navigation.tsx component to facilitate smooth navigation within the Donors Dashboard.
**Reporting Directory:** …
=> Donors Dashboard Feature: Frontend Implementation and Routing

server/Dockerfile
*Brief description of changes*
*Potential areas of concern that you would like looked at more closely*
*How you verified that these changes work*
*Link to corresponding issue*
*If you're on Mac, please include whether you are on an Intel or M-series CPU*
=> comment in server

client/src/components/Ticketing/mainpage/hero.tsx
Added Previous and Next buttons/arrows on the main event display page.
Before:
(1/2):
(2/2):
After:
(1/2):
(2/2):
Currently no unintended side effects
Manual Testing
https://pdx-hkaus.atlassian.net/browse/TIC-75
Win10/Chrome
=> TIC-75 Improved desktop usability with navigation button for showings

LICENSE, client/src/components/Ticketing/cart/Cart.tsx, client/src/components/Ticketing/mainpage/Navbar.tsx, client/src/components/Ticketing/mainpage/Seasonalt.tsx, client/src/components/Ticketing/mainpage/eventcard.tsx, client/src/components/Ticketing/mainpage/footer.tsx, client/src/components/Ticketing/mainpage/hero.tsx, client/src/components/Ticketing/ticketingmanager/udash_navbar.tsx, client/tests/example.spec.ts
1. Increased size of hamburger and close icons (also increased margin on the right) on main mobile page
2. Increased responsiveness beyond `sm` breakpoint size
3. Updated copyright and license year to "2023"
4. Added alt text where applicable
5. Tuned margins across the board
**Before:**
**After:**
_**Note:** It says there was a plethora of changes in `cart.tsx` but the only changes that were made was the removal of `h-screen` and removing the highest div_
Shouldn't be any
Visually inspected all areas to ensure functionality wasn't lost.
[TIC-88](https://pdx-hkaus.atlassian.net/browse/TIC-88)
Windows 11
[TIC-88]: https://pdx-hkaus.atlassian.net/browse/TIC-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-88] increased mobile usability of main WonderTix page

client/src/App.tsx, client/src/components/CRM/Dashmain.tsx, client/src/components/Ticketing/ticketingmanager/Season/SeasonMain.tsx, client/src/components/Ticketing/ticketingmanager/Udashmain.tsx, client/src/components/Ticketing/ticketingmanager/dashboard.tsx
Added the Seasons Ticketing Dashboard route. Please note, I left comments in the files that I actually changed, the other are just prettier formatting changes.
No risks, simply adding the route and dashboard link so admin can visit seasons page. Currently doesn't show anything.
Able to see it within ticketing manager UI
https://pdx-hkaus.atlassian.net/jira/software/projects/TIC/boards/1?selectedIssue=TIC-77
M2 Mac
=> TIC-77: Create select season and edit season page

client/src/components/Ticketing/ticketingmanager/showings/InstancesPage.tsx
Added filter drop down list: Active, Inactive, All
N/A
Manual
https://pdx-hkaus.atlassian.net/browse/TIC-60
Win10/Chrome
=> TIC-60 Added Frontend Event Filter

client/src/App.tsx, client/src/components/Ticketing/ticketingmanager/Refund/RefundOrderTicket.tsx, client/src/components/Ticketing/ticketingmanager/Refund/RefundOrderTicketMain.tsx, client/src/components/Ticketing/ticketingmanager/dashboard.tsx
TIC-86 Added Refund Button/Page to Ticket Manager
None, just front end/cosmetic changes
Manual Testing
https://pdx-hkaus.atlassian.net/browse/TIC-86
Win10/Chrome
=> TIC-86 Added Refund Button/Page to Ticket Manager

client/e2e/dashboard.test.ts, client/e2e/pages/dashboardPage.ts
Test for Wondertix Ticketing Dashboard was created. 
Mainly used to test if all the links in the dashboard behave as we expect
Verified working locally and in CI via Github Actions
If the name of the page button in the Ticketing Dashboard has been changed, the test needs to be adjusted again
Test Run vs local deployment in VSCODE.
[DEP-50]
Windows
[DEP-50]: https://wondertix.atlassian.net/browse/DEP-50?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Ticketing Dashboard Test

server/cloudbuild.yaml
Altered cloudbuild.yaml for the server. Added secrets directly to the file to link up
with the secrets loaded to GCP. Adding encryption to the process to avoid transfer 
of plain text keys.
Triggers could have issues building correctly, but this has already been tested.
Ran triggers from my branch to verify success.
(https://wondertix.atlassian.net/jira/software/projects/DEP/boards/1?assignee=712020%3Af5afac34-8342-4273-ad0b-ac9b138109fa%2C712020%3Aef81f312-676f-4565-bc0c-b66e14c39114&selectedIssue=DEP-62)
Windows 10
=> Dep 62 secrets

.github/workflows/E2E_deployment.yml
Change the URL for the second test
Null
on local
[DEP-78]
Windows
[DEP-78]: https://wondertix.atlassian.net/browse/DEP-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-78] change the URL for the test

.github/workflows/E2E_deployment.yml
fix the missing username and password for #414
null
local
[DEP-78]
Windows
[DEP-78]: https://wondertix.atlassian.net/browse/DEP-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-78] Hot fix for #414

.github/workflows/E2E_request.yml
added a triggering condition, which is a test file for the request
no
no
[DEP-82]
Windows
[DEP-82]: https://wondertix.atlassian.net/browse/DEP-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DEP-82 added a new test file

client/e2e/EventsPage.spec.ts, client/e2e/pages/EventsPage.ts, client/e2e/testData/ConstsPackage.ts, client/src/components/Ticketing/ticketingmanager/showings/ShowingUpdated/EventShowingView.tsx
This branch is for testing the events and showings part in the Manage Ticketing page. 
In this branch, we added EventsPages.ts, and Events Page.spec.ts.
We tested the functionality to create an event and modify the event information, as well as the functionality to create and modify the showing information. We simulated a story that some users might follow and tested that all the relevant buttons worked properly.
1. Sometimes during testing, the "example.spec.ts" sometimes fails, but sometimes it does. 
2. When we test the functionality of creating and canceling the showing, we just use only one specific string--"Date: Wed, Oct 11 2023Time: 12:10 AM" as a keyword for searching the most recently created showing, it seems to lack flexibility, but for now, our tests seem relatively robust. …
=> Dep 51 showings test final

.github/workflows/E2E_deployment.yml, .github/workflows/E2E_request.yml, .github/workflows/E2E_tests.yml
setting all the URL as secret
no
[DEP-82]
Windows
[DEP-82]: https://wondertix.atlassian.net/browse/DEP-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Dep-82] fix the URL 

client/package-lock.json, client/package.json
Installed prettier as a dev dependency to allow team to be consistent in formatting code
No risk
Test to see if prettier was run
https://pdx-hkaus.atlassian.net/jira/software/projects/TIC/boards/1?selectedIssue=TIC-33
M2 Macbook
=> TIC-33: Install Prettier as a dev dependecy

server/src/controllers/orderController.ts
Fixed issue where comped orders were not refundable. 
NA
Manual testing
NA
Apple Silicon
=> [TIC-123] Comped orders are not refundable

client/src/components/Ticketing/GroupToggle.tsx, client/src/components/Ticketing/ticketingmanager/showings/InstancesPage.tsx
Completed the back-end implementation to the new group toggle button for showings using the new prisma api. Results in being able to filter the events based on active/inactive/all events to be displayed.
Unsure if there is, settings are strict to the 3 options.
Manual Testing:
[*Link to corresponding issue*](https://pdx-hkaus.atlassian.net/browse/TIC-53)
Win10/Chrome
=> TIC-53 Back-end implementation of Active/Inactive/All Events for Showings

client/src/components/Ticketing/GroupToggle.tsx, client/src/components/Ticketing/ticketingmanager/Doorlistpage/doorlist.tsx
Replaced checkbox in doorlist with a variant of the `ShowingActivenessToggle`. To do this I added a new prop which is enabled by default that determines if the `INACTIVE` option is shown.
None
[TIC-121](https://pdx-hkaus.atlassian.net/browse/TIC-121)
Windows 11
[TIC-121]: https://pdx-hkaus.atlassian.net/browse/TIC-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-121] Replaced checkbox with ShowingActivenessToggle in Doorlist

client/src/App.tsx, client/src/components/Authentication/protected-route.tsx
Updated the ProtectedRoute component to verify that a user is an admin in addition to the current
verification that they are logged in.
NA
Manual testing
Closes #446 
M1 Mac
=> [TIC-136] Updated protected route to require admin permissions

client/src/components/Ticketing/ticketingmanager/RefundOrders/RefundOrders.tsx
Updated confirmation `PopUp` message for Refunds page.
None
[TIC-141](https://pdx-hkaus.atlassian.net/browse/TIC-141)
Windows 11
[TIC-141]: https://pdx-hkaus.atlassian.net/browse/TIC-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-141] Updated Refund PopUp confirmation message

client/src/components/CRM/Contacts/ContactOneResult.tsx, client/src/components/Ticketing/GroupToggle.tsx, client/src/components/Ticketing/checkout/CompleteOrderForm.tsx, client/src/components/Ticketing/checkout/FormInput.tsx, client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminCheckout.tsx, client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminCompleteOrderForm.tsx, server/src/controllers/eventController.service.ts, server/src/controllers/eventController.ts
Added validations and requirements for the fields: `First Name`, `Last Name`, and `Email`.
Fixed bug with `ShowingActivenessToggle` so now there will always be one option selected instead of none.
Fixed bug with `FormInput` so that `name` and `type` are now being properly passed to the inner input.
Manual testing and checking orders on the contact page.
[TIC-119](https://pdx-hkaus.atlassian.net/browse/TIC-119)
Windows 11
[TIC-119]: https://pdx-hkaus.atlassian.net/browse/TIC-119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-119] Add requirements to Admin Purchase Form

client/src/components/Ticketing/ticketingmanager/showings/ShowingUpdated/TicketTypeUpdateTable.tsx
removed module import that was not being used and was causing E2E tests to fail.
N/A
E2E tests pass
N/A
Windows
=> Remove module import that is not being used.

client/src/App.tsx, client/src/components/Ticketing/ticketingmanager/DoorList/DoorList.tsx, client/src/components/Ticketing/ticketingmanager/DoorList/DoorListmain.tsx
Changed the method in which dates are formatted in the doorlist to no longer need to do a `+1`. Previously, I believe there was some time zone shenanigans between putting only a date in the `Date()` constructor and then also getting the ISOString. So now we are passing in both a date and time consistent with how we use `Date` objects throughout WonderTix. For more info, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format.
Can't be worse than how it is already.
Windows 11
=> Changed Doorlist Method for Formatting Dates

server/prisma/migrations/20231121021809_add_season_ticket_type_price_table/migration.sql, server/prisma/schema.prisma, server/src/controllers/SeasonTicketTypePriceDefaultController.ts, server/src/controllers/seasonTicketTypePriceDefaultController.ts, server/src/server.ts
Adding a table and API calls as needed to modify ticket type prices by season ID.
Only includes backend functionality for the new table and does not include integration with the current schema.
Functionality includes:
- PUT: Accepts an array of season ticket type prices and adds/updates/deletes accordingly.
- GET: Retrieves all season ticket type prices linked to a specific season ID.
NA
Manual testing on Swagger page.
[Jira Ticket](https://pdx-hkaus.atlassian.net/jira/software/projects/TIC/boards/1?selectedIssue=TIC-135)
M1 Mac.
=> TIC-134-A: adding SeasonTicketTypePriceDefault table and APIS

client/src/components/Ticketing/ticketingmanager/Season/components/SeasonContainer.tsx
Fix the loading screen positioning of the seasons page to be centered
No risk
Test in the UI
https://pdx-hkaus.atlassian.net/jira/software/projects/TIC/boards/1?selectedIssue=TIC-128
M2 Macbook
=> TIC-128: Fix loading screen positioning for seasons page

client/src/components/Ticketing/event/TicketPicker.tsx
Fixed bug where dates with multiple showings showed up in ticket selection multiple times
None come to mind
Manual testing
N/A
Windows
=> [TIC-138] Fixed bug where dates with multiple showings showed up in ticket selection multiple times

.github/workflows/client_test.yml
Added the client unit test
null
local
Windows
=> Add auto client unit test

client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminPurchase.tsx
Added minor update to truncate columns on admin purchase page to that the selection box does not extend past the bounds of the cell width.
Just added some css elements
Manual testing
N/A
Windows 11
=> [TIC-109-update] Added minor update to truncate columns on admin purchase page

client/src/components/Ticketing/ticketingmanager/Season/components/EventCard.tsx
Fix error where default season image was being shown for an event
Little to none
Checked in the UI
No issue
M2 Macbook
=> Fix event image in seasons page

client/e2e/EventsPage.spec.ts, client/e2e/doorListTest.spec.ts, client/e2e/pages/seasonsPage.ts, client/e2e/seasonsPage.spec.ts, client/e2e/testData/ConstsPackage.ts
Refactored existing tests to use the UUID function.  Additionally did some minor linting work and moved the scope of a few consts in the seasons tests.
Backwards compatibility with the old EventsInfo2-6 objects has been removed.  Future EventsInfo objects will have to be instantiated as:
`const currentEvent = new EventsInfo(EventsInfoTemplate#);`
The EventsInfo class members otherwise remain the same, so working with those objects is otherwise unchanged.
editEevents still needs to be refactored.
Any tests not merged will need to be refactored to remove dependency on the old EventsInfo# definitions.
Ran local tests
https://wondertix.atlassian.net/browse/DEP-102?atlOrigin=eyJpIjoiYzBhYTdhMmViZWU0NDU3YmExODk5MDczYjM0NGRlOGQiLCJwIjoiaiJ9
Windows 11
=> Dep 102 refactor tests to implement UUID

client/src/components/CRM/Navigation.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/ExchangeSalesPriceLevelReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/GrossSalesPriceLevelReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/NetSalesPriceLevelReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/NetSalesSummaryReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/PaymentSummaryReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailyReports/SalesSummaryReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailySalesReport.tsx, client/src/components/CRM/Reporting/DailySalesReport/DailySalesReportMain.tsx, client/src/components/CRM/Reporting/DailySalesReport/FilterReports/FilterEventCode.tsx, client/src/components/CRM/Reporting/DailySalesReport/FilterReports/FilterOptions.tsx, client/src/components/CRM/Reporting/DailySalesReport/FilterReports/FilterPriceLevel.tsx, client/src/components/CRM/Reporting/DailySalesReport/FilterReports/FilterRange.tsx, client/src/components/CRM/Reporting/DailySalesReport/FilterReports/FilterReports.tsx, client/src/components/CRM/Reporting/DailySalesReport/ScheduledReports/DeliveryOptions.tsx, client/src/components/CRM/Reporting/DailySalesReport/ScheduledReports/FrequencyOptions.tsx, client/src/components/CRM/Reporting/DailySalesReport/ScheduledReports/ReportOptions.tsx, client/src/components/CRM/Reporting/DailySalesReport/ScheduledReports/ScheduleReportsForm.tsx, client/src/components/CRM/Tasks/Modals/CreateTask.tsx, client/src/components/CRM/Tasks/Modals/UpdateTask.tsx
These are updated code changes and bug fixed for CRM `Task Manager` & `Daily Sales Reports` 
1. Updated styling and formate
2. Updated Routes and Navigation for Task Manager.
3. Removed dropdown Navigation for Tasks in menu bar.
4. Updated Component responsiveness Daily Sales Reports.
1. Fixed bug in email validation.
2. Fixed radio buttons for Daily Sales Reports.
3. Fixed bug Create and Update modals for Task Manager.
There are no potential risks associated with these code changes.
They are simply cosmetic modifications to the UI of the Task Manager and Daily Sales Reports.
Manual testing and inspecting the console logs.
macOS: Sonoma 14.0
M-series CPU
=> CRM Reports Branch

client/e2e/doorListTest.spec.ts, client/e2e/pages/EventsPage.ts, client/e2e/pages/doorListPage.ts, client/src/components/Ticketing/GroupToggle.tsx
Added test to check door lists for both active and inactive events, as well as ensure the correct customer information is reflected.
None.
Passed tests locally.
https://trello.com/c/cXTDMuoC/26-16-implement-door-list-testing
Windows
=> FW23-16 Doorlist Tests

client/src/components/CRM/Contacts/ContactCard.tsx, client/src/components/CRM/Contacts/ContactPopUp.tsx, client/src/components/CRM/Contacts/ContactResults.tsx, client/src/components/CRM/Contacts/Contacts.tsx, client/src/components/CRM/Contacts/contactUtils.ts, client/src/components/CRM/Tasks/Search.tsx, server/src/controllers/contactController.ts
Added ability to edit a contact, and refactored the deletion of a contact.
* Added new buttons for editing and deleting a contact
* Added confirmation popup when deleting a contact
* When deleting a contact, the page now updates on deletion so the contact disappears (instead of persisting until a refresh) [this is also the case for the new editing]
* If a contact can not be deleting, a PopUp shows the error
* General visual and accessibility improvements
* Added "No results" message when a search returns nothing
Just to note:`ContactResults` got refactored into `ContactCard`.
I deleted a reference to `ContactResults` within a Task-based Search component. But after looking into things, it appears that this Task component (as well as many others) were replaced with the recent task …
=> [WT-544] Add ability to edit a contact

server/src/server.ts
Minimal change in the server directory to get migrations to run on deploy
win10
=> Minimal change in the server directory to get migrations to run on deploy

server/src/server.ts
Reverts "Minimal change in the server directory to get migrations to run on deploy (#556)"
Now need some change to the server to trigger the staging database migrations when I deploy to it
win10
=> Revert "Minimal change in the server directory to get migrations to run on deploy (#556)"

client/src/components/Authentication/auth0-provider-with-history.tsx
Minimal change to the client to get a new revision to build in cloud run
win10
=> Minimal change to the client to get a new revision to build in cloud run

client/e2e/pages/mainPage.ts, client/src/App.tsx, client/src/components/Ticketing/checkout/CompleteOrderForm.tsx, client/src/components/Ticketing/donation/OnlyDonatePage.tsx, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/mainpage/EventCard.tsx, client/src/components/Ticketing/mainpage/Main.tsx, client/src/components/Ticketing/mainpage/Navbar.tsx
**Changes to user facing events page:**
- Renamed “See Showings” to “Select Date & Time”
- Removed “add a concessions ticket” checkbox
**Season tickets section:**
- Renamed navbar header to "Subscriptions"
- Deactivated (temp remove) subscription sales
**Cart:**
- Country and phone number are no longer required
**Donate page:**
- Deactivated
Visually looked.
#563 
macOS M2
=> [WT-563] Quick customer-facing changes

client/e2e/pages/doorListPage.ts, client/e2e/testData/ShowingInfo.ts, client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminPurchase.tsx, client/src/components/Ticketing/ticketingmanager/DoorList/DoorList.tsx, client/src/components/Ticketing/ticketingmanager/Event/components/EventShowingView.tsx, client/src/components/Ticketing/ticketingmanager/RefundOrders/RefundOrders.tsx, server/src/api/doorlist/doorlist.router.ts, server/src/api/doorlist/doorlist.service.ts
Updated doorlist API and door list front end to display contact email, phone number, and address.
Also updated the doorlist to export with a more informative title, rather than just "WonderTix".
**CSV File:**
May have missed a spot when updating the API.
Manual testing of doorlist.
#542 
macOS M2
=> [WT-542] Added email, phone, and address to Door List

client/src/components/Ticketing/ticketingmanager/Event/components/EventShowingForm.tsx, client/src/components/Ticketing/ticketingmanager/Event/components/EventShowingView.tsx, client/src/components/Ticketing/ticketingmanager/Event/components/EventShowingsContainer.tsx, client/src/interfaces/showing.interface.ts, server/src/controllers/eventInstanceController.ts
Added a `Sold` column that displays how many tickets of a particular ticket type in a particular showing have been sold.
There could be an area where the new `ticketssold` attribute could cause issues if it is being passed around inappropriately.
Manual testing (see screenshot).
#566 
macOS M2
=> [WT-566] Added "Sold" column to showing ticket types

client/src/components/Ticketing/IconButton.tsx, client/src/components/Ticketing/Icons.tsx, client/src/components/Ticketing/ticketingmanager/DiscountCodes/DiscountCodes.tsx, client/src/components/Ticketing/ticketingmanager/DiscountCodes/discountUtils.tsx, client/src/components/Ticketing/ticketingmanager/TicketTypes/TicketTypes.tsx, client/src/components/Ticketing/ticketingmanager/TicketTypes/ticketTypeUtils.ts, server/src/controllers/ticketTypeController.ts
Improved the Ticket Type screen for error handling and increased intuitiveness.
* Added `Edit`, `Save` and `Cancel` icon buttons.
* Money fields display as monetary values
* Added lots of error handling to display to the user when...
* Cannot delete a ticket type
* Provided invalid fields (empty description, negative price or concessions price)
* Ticket type doesn't exit
* etc
* Condensed visual components
* Removed "default ticket type" chip since that will no longer be necessary soon
N/A
Manual testing with constant creation, editing and deleting ticket types.
#590 
macOS M2
=> [WT-590] Improved Ticket Type Management UI

client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/event/EventShowings.tsx, client/src/components/Ticketing/event/TicketPicker.tsx
Increased the size of the UI text on the main ticket select because was told it could be too small for elderly customers
Not sure how to test this on mobile but it should be enlarged there too
Opened event showing view and inspected text
https://github.com/WonderTix/WonderTix/issues/596
Windows 11
=> [WT-596] Increased the size of the UI text for event showings and ticket selection

client/src/components/CRM/Navigation.tsx, client/src/components/Ticketing/mainpage/Navbar.tsx, client/src/components/Ticketing/ticketingmanager/udash_navbar.tsx
added useRef to close navbar without rerender
none really
tested locally
*Link to corresponding issue*
https://github.com/WonderTix/WonderTix/issues/243
Mac M1 Pro
=> NavBar goes away when click outside

cloudbuild.yaml, gcp/scripts/build-client.sh
Small change to add the react web socket env var as a build argument
=> added WEBSOCKET_URL var to build-client

client/package.json, client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminPurchase.tsx, client/src/components/Ticketing/ticketingmanager/ticketingSlice.spec.ts, client/src/components/Ticketing/ticketingmanager/ticketingSlice.ts, server/src/controllers/eventInstanceController.ts
Update sold out indicators to reference the smaller of showing availability or ticket restriction availability.
It is possible that I missed updating a component that references ticket availability. 
Manual testing
#640 
M1 Mac
=> [WT-640] Update sold out Indicator to reference Ticket Restriction level availability

client/src/components/CRM/Reporting/DonationSummaryReport/DateRange.tsx
*Fixed Date picker in donation summary report*
*Potential areas of concern that you would like looked at more closely*
*None*
*Link to corresponding issue*
*Mac Intel Using Safari*
=> Enhanced Date picker in Donation Summary Report

docs/reset-db.md
Updated the database reset documentation to be more concise and not require the VM.
=> Updated Database Reset Docs
