server/src/api/donations/donations.router.ts, server/src/api/events/event.router.ts, server/src/api/events/event.service.ts, server/src/interfaces/Showing.ts
Added a PUT route for /events/instances. Cleaned up GET /events and return numShows as well to reduce work in client for ManageEvents page. Cleaned up PUT /events. Updated Showing interface to match database schema (still has tickettype field that is not in the event_instances table). Removed redundant /events/list route.
Issue #55 
N/A
Tested new endpoint as well as modified existing endpoints by making calls in Postman.
=> Added PUT /events/instances/:id, cleaned up other routes

server/src/api/accounts/accounts.service.ts, task_sql/wtix_dump_030422.sql
Minor changes to users table. I removed the pass_hash column and added a auth0_id column to the users table. I also added action to Auth0, so this information is posted to API when users create accounts.
Issue #70
Creating accounts in ManageAccounts page is now going to be broken. That needs to be updated to utilize Auth0 to create accounts instead. 
* NPM Version:
=> Removed pass_hash, added auth0_id to users table

server/src/api/tickets/ticket.service.ts
Modified getValidTicketTypes query so that the Pay What You Can ticket type is not returned. Calls to the route `api/tickets/types` will not return the Pay What You Can ticket type to the client anymore so that it is not displayed in the Manage Ticket Types page. This is so that it will not get accidently deleted which would have breaking consequences.  
Issue #
none
Verified result with Postman and calls from the client
...
* Operating System: win10
* NPM Version:
none
=> Modified getValidTicketTypes query so that the Pay What You Can ticket type is not returned

client/src/components/Ticketing/Pop-up.tsx, client/src/components/Ticketing/ticketingmanager/Events/Add_event/CreateEventPage.tsx, client/src/components/Ticketing/ticketingmanager/showings/showing/showing.tsx, client/src/interfaces/popup.interface.ts
Issue #152 
When the "Delete Event" button is pressed in the View Showing page, the modal shows up but the user has to scroll to the top of the page to see it. Fixed the issue so that it shows up in the center of the user's screen. Also dimmed the background when the modal pops up so that it's obvious that the user must interact with it.
Issue #146 
In the "Add Event" page, after clicking the "Save" button, a modal pops up indicating it was successfully saved. Both the "Proceed" and "X" button redirect the user to the "Manage Events" page. Fixed the issue by changing the "X" button behavior - it now closes the modal and redirects the user to the "Edit Event" page of the newly added event. Also changed the color of the "Proceed" button from red to green, so it makes more sense.
Issue #152 …
=> Centered "Delete Event" popup in Showings page and changed "X" button behavior in Add Event page

client/src/components/Authentication/auth0-provider-with-history.tsx, docker-compose.yml, server/src/auth.ts, server/src/server.ts
Allow logging into swagger to run restricted routes
Issue #
Some hardcoded values have been moved to env varables
Add the following to your `.env`
```
AUTH0_AUDIENCE=https://localhost:8000
AUTH0_CLIENT_ID=riiCcrxD0o7N7oArqgWTTTniMmYM6WiL
AUTH0_URL=https://wtix-dev.us.auth0.com
```
Verify container builds and you can log in
I plan on doing a documentation PR after my current open PRs that covers this and the docker improvements pr
None
=> Swagger authentication

client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, server/src/api/events/event.service.ts
Before, the user was not able to save the event without filling out the showings because of an unknown error; after some digging, I found out that it was because the datetime and starttime could not be parsed if they were empty. So now, if they are empty, instead of erroring, it will create a date with the default value of 20200101 and time of 0000. This allows the user to create an event without needing to add ticket types and adding a datetime or a start date.
Issue #
...
* NPM Version:
Provide any additional information that …
=> Backend event fixes

README.md
This is just a document update to the readme.
I am removing the instructions for local installs to simplify things. Docker is preferred to ensure everyone is on the same version of dependencies. 
Changed the headings to a simple list.
Included information about `.env` file, swagger docs and having to type `thisisunsafe`
=> update readme with new docker instructions

server/src/api/ticket_types/ticket_types.router.ts, server/src/models/TicketType.ts, server/src/server.ts
Adds a new router with a route for editing an existing ticket type.
`PUT /api/ticket-types/{id}`
Issue #
All code is new so no BC changes.
...
No tests written because they have been written to focus on the [standardization task](https://github.com/WonderTix/WonderTix/issues/222) which may do things differently as a v2 api.
This is done in a new router to have `ticket-types` as the resource in the url. The ticket router includes routes for tickets and tickettypes adding some confusion. The ticket type related routes should be moved over to the new router or we should just focus on a new api, deprecating the old one.
=> Edit ticket types

client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx, client/src/components/Ticketing/ticketingmanager/Events/deleteConfirm.tsx, client/src/components/Ticketing/ticketingmanager/Events/showListController.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, client/src/interfaces/showing.interface.ts
- If the user chooses a ticket type but selects ‘Select a ticket type’, the form will still activate on save but that ticket type isn’t saved to db. 
- Once the showing is added to the form, all inputs (except for ticket types) should be required.
- At some point, a modal added to confirm that the user wants to delete a showing before the showing is removed from the page.
- A modal added indicating that the user should add a showing if they haven’t added one in order to save the form.
Issue #
...
* NPM Version:
Provide any …
=> UI Changes

client/src/components/CRM/Accounts/ManageUsers/ManageAccounts.tsx, client/src/components/Ticketing/ticketingmanager/Events/Edit_event/EditEventPage.tsx, client/src/components/Ticketing/ticketingmanager/Events/EventForm.tsx, client/src/components/Ticketing/ticketingmanager/Events/ManageEvents.tsx, client/src/components/Ticketing/ticketingmanager/Events/deleteConfirm.tsx, client/src/components/Ticketing/ticketingmanager/Events/showListController.tsx, client/src/components/Ticketing/ticketingmanager/Events/showingInputContainer.tsx, client/src/interfaces/showing.interface.ts, server/src/api/events/event.service.ts
Use this event fix instead, there was too many changes in the other one. 
- Refactored showingInputContainer to use hooks and conditional rendering instead of vanilla JS DOM. 
- Cleaned up code
- Allows user to save event without clicking the save button for each showing
- Saving data with the edit button now sends to sever using this format
- ![image](https://user-images.githubusercontent.com/62050214/225426323-c0ae3179-7f7f-41c1-9321-740ac18d3df7.png)
- Clicking edit will correctly display time and date
- Fixed bugs regarding removing shows.
Issue #145 
Editing still does not work because the eventid is undefined when editing. 
Edit looks like it takes in a different object.
...
* Operating …
=> WIP: Add event without clicking save show

server/src/api/events/event.service.ts, server/src/api/tickets/ticket.router.ts
edit event works but when a showing is edited, it would go to the bottom of the page as the last showing because the query to get the event instance ordered it by eventID. If you click on a showing, the eventid for each event instance (showing) would be 32 (for example). This means when you edit a showing, it would put that showing last so when you click edit again, it would put that updated showing to the end. This edit orders it by eventinstanceID so it will stay consistent on the page even after editing.
Issue #
...
* NPM Version:
Provide a brief explanation for why the checklist was not …
=> fix documentation and order of showings for edit showing

README.md, client/package.json
Mkcert is fixed so that the certificate warning on Chrome will no longer appear. This is done by pointing SSL_CRT_FILE to /usr/app/localhost.pem and SSL_KEY_FILE to /usr/app/localhost-key.pem in the client package.json file.
This requires the user to copy the certificate keys from the server to the client folder for the docker builds to work.
Readme updated to reflect the need to copy the local certificate public and private keys into the client folder
This requires the user to copy the certificate keys from the server to the client folder for the docker builds to work.
Certificate Warning no longer appears. 
#297 
Mac M Series
=> [DEP-22] mkcert fixed #297

server/Dockerfile
Fixed DB_USER to DB_PORT in the variable calling the wait-for-it.sh script since the docker logs were saying 'nc: invalid port postgres' and now it works fine since it's not being passed the ip:username, it's now the ip:port as it should be.
None
Passed on Docker, error not showing in the logs any more
NA
macOS (intel) 13.0
=> Fixed DB_USER to DB_PORT

.gitignore, client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/ticketing/ticketingSlice.spec.ts, client/src/components/Ticketing/ticketingmanager/ticketing/ticketingSlice.ts
When building the client container, there would be several eslint warnings and a warning about a missing parameter in one ticketingSlice test. These have been resolved by adding the parameter and fixing the eslint spacing issues.
Also added `client/build` to the .gitignore as it houses temporary dev files we wouldn't want to commit to the GitHub repo.
There is a possible risk with adding `client/build` to the .gitignore, but seeing as no build files currently exist in the repo, I don't feel as though they are necessary.
Checked the docker client console before and after making the changes.
Jira Ticket [TIC-38](https://pdx-hkaus.atlassian.net/browse/TIC-38).
Windows 11
[TIC-38]: https://pdx-hkaus.atlassian.net/browse/TIC-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> [TIC-38] Fixed ticketingSlice warnings and other client warnings appearing in console

WonderTix.code-workspace
Added the `./server/` folder to the WonderTix codespace file so VSCode stops complaining that jest is removed from the server and it can't find a valid jest project
None, jest isn't used at the moment
Opened the WonderTix workspace file in VSCode and saw no more complaining or issues
N/A
macOS Sonoma (14.0), intel
=> [VSCode] Ignore Server Folder for Jest tests

client/src/components/Ticketing/mainpage/Navbar.tsx
On changing screen size, the profile picture of the main page navbar would shrink horizontally. The profile picture should stay the same until the layout snaps to mobile size. This small change fixes the issue.
Compressed profile picture before fix:
None
Now as the screen gets smaller the profile image no longer appears to compress. This was tested on Google Chrome.
[https://github.com/WonderTix/WonderTix/issues/241](https://github.com/WonderTix/WonderTix/issues/241)
Mac: Apple M1
=> [DON-91] fixed navbar profile image shrinkage

client/tests/example.spec.ts
Added 100s timeout for client and and 120s timeout for server to load and fixed eslint spacing issues in test file.
N/A
This PR passes with flying colors.
N/A
N/A (GitHub Actions)
=> Add Timeouts to E2E Tests

server/prisma/migrations/20231012025406_change_event_season_i_dfk_constraint/migration.sql, server/prisma/schema.prisma, server/src/controllers/seasonController.ts, server/src/server.ts
- Updated the OpenAPI specification for the seasons swagger page API endpoint to include the new imageurl data column that was added. Specifically for the endpoints getSeason, getAllSeason, and updateSeason.
- Fixed the deleteSeason endpoint because previously, we could not delete a season since there are events that reference it. I ran a database migration to make the seasonID foreign key of the Events table optional so that we can now delete seasons even when there are events that reference them. This change will make the seasonID column for events NULL if a season that it references is deleted.
Very minimal, although DB migrations always run the risk of having unseen consequences. However, considering  season was never utilized to begin, the migration shouldn't have any negative …
=> TIC-77: Update swagger page and fix api for seasons

.github/workflows/E2E_deployment.yml
E2E tests after merge to main
Create a Github Action via workflow.yaml, it will trigger playwright to run e2e tests against the specified GCP dev client URL with a 5 minute wait prior to running. 
Test will run after a merge to main regardless of dev deployment success or failure. Will be iterating on this. 
E2E tests have been verified to run but not from a merge to main. Merging to main to test. 
[DEP-57]
Windows
[DEP-57]: https://wondertix.atlassian.net/browse/DEP-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DEP-57] E2E tests after merge to main

client/cloudbuild.yaml, server/cloudbuild.yaml, server/src/api/db.ts, server/src/server.ts
- Expands condition in server code to detect `ENV` value of `'prd'`.
- Parameterizes memory and CPU allocation in `cloudbuild.yaml`.
- Bumping up resources allocated to `stg` and `prd` will increase cost.
- Using this branch, I've deployed both client and server across `dev`, `stg`, and `prd` without issues.
- Client: https://wtix-client-prd-3ps4rkx4ga-wl.a.run.app/  
- Server: https://wtix-server-prd-3ps4rkx4ga-wl.a.run.app/
- Link: [*DEP-75: Set up `prd` environment*](https://wondertix.atlassian.net/browse/DEP-75)
- Ubuntu 22.04
=> DEP-75: set up `prd` environment

client/cloudbuild.yaml, server/cloudbuild.yaml
Small change: sets a maximum number of instances for Cloud Run autoscaler. The default is 100, which is kind of crazy for our purposes, and now that we've bumped some of our CPU allocation up, Cloud Run doesn't like the possibility of 100 instances.
I suppose it's possible we could suddenly get slammed with traffic and have to scale higher than 10, but I don't foresee that happening any time soon.
I built and deployed from this branch to `dev`, then promoted across `stg` and `prd`. No issues, and I've got receipts:
- https://console.cloud.google.com/cloud-build/builds;region=us-west2/8ca36ce8-bf53-4b14-8d74-5e6463744c11?project=wondertix-app
- https://console.cloud.google.com/cloud-build/builds;region=us-west2/ffc3e42c-a3b7-4920-a280-b85d4754c7c9?project=wondertix-app
- …
=> DEP-77: explicitly set max value for Cloud Run autoscaling

client/cloudbuild.yaml, server/cloudbuild.yaml
Previously this feature was manually enabled in our Cloud Run deployments. It effectively doubles the CPU instances allocated while a container spins up in order to shorten that startup time.
However, because this option wasn't specified in our `cloudbuild.yaml` files, migrating to a new Cloud Run revision meant it would be disabled by default.
This branch adds the `--cpu-boost` flag to the deploy step of our `cloudbuild.yaml` files to ensure this option is enabled without requiring manual intervention in the GCP web UI.
- Docs: https://cloud.google.com/run/docs/configuring/services/cpu#startup-boost
None, really. We've already been using this feature for weeks.
I manually deployed these changes to the `dev` environment. Here are the build logs:
- Server: …
=> DEP-80: add CPU boost to improve container startup time

server/Dockerfile.dev
Added two lines to the Docker.dev file to provide the server with correct timezone (PST).
Changes are already reflected in our previous Dockerfile, minimal impact.
Tested my branch on both the client and server and both builds passed.
(https://wondertix.atlassian.net/jira/software/projects/DEP/boards/1?selectedIssue=DEP-66)
Windows 10
=> Added timezone to Docker.dev file

server/src/api/doorlist/doorlist.service.ts
Added back missing parameter for General Admission - Adult ticket type. Also fixed jsdoc while I was at it.
None
Manually tested
N/A
Windows 11
=> Fix doorlist page by only counting GA-Adult ticket types in API call

client/e2e/dashboard.test.ts, client/e2e/pages/dashboardPage.ts, client/src/App.tsx, client/src/components/Ticketing/ticketingmanager/RefundOrders/RefundOrders.tsx, client/src/components/Ticketing/ticketingmanager/RefundOrders/RefundOrdersMain.tsx, client/src/components/Ticketing/ticketingmanager/dashboard.tsx
Renamed instances of `Refund Ticket` to `Refund Orders` so it better represents the functionality of Refunds. This is something that I noticed after-the-fact. I also Renamed some of the files so that the components' names match their file names. Also some prettier changes
Also updated the E2E tests to include refunds and seasons pages.
None
Manual testing
[TIC-118](https://pdx-hkaus.atlassian.net/browse/TIC-118)
Windows 11
[TIC-118]: https://pdx-hkaus.atlassian.net/browse/TIC-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-118] Rename Refund Ticket to Refund Orders

client/src/components/Ticketing/ticketingmanager/Season/components/SeasonEvents.tsx, client/src/components/Ticketing/ticketingmanager/Season/components/SeasonInfo.tsx, client/src/components/Ticketing/ticketingmanager/Season/components/utils/apiRequest.ts, server/src/controllers/eventController.ts
Update Season page to utilized most-up-date events API that was changed recently. 
Little to minimal risks, simply updated which API was being used and removed code that was no longer needed
Test in the UI to ensure everything still functions as normal and double check database for changes.
https://pdx-hkaus.atlassian.net/jira/software/projects/TIC/boards/1?selectedIssue=TIC-124
M2 Macbook
=> TIC-124: Migrate Season page to utilized v2 events API instead of v1

scripts/deploy/server.sh
- Adds Stripe webhook secret to server deploy script.
- Corresponding webhook endpoints have been added on Stripe.
- Secrets have been added to Secret Manager on GCP.
- Only tested on the `dev` client.
- Secrets need to be changed when we migrate Stripe accounts.
- Manually tested Stripe checkout on `dev` client:
- Built and deployed `dev` server to make sure script doesn't break anything:
- https://console.cloud.google.com/cloud-build/builds;region=us-west2/2de768e3-cbfb-40e8-919a-b6934978d5dc?project=wondertix-app
- [*DEP-90: set up Stripe webhooks*](https://wondertix.atlassian.net/browse/DEP-90)
- Ubuntu 22.04
=> DEP-90: add Stripe webhook secret

server/src/controllers/orderController.service.ts
Fixed an issue where it would show the order time 8 hours ahead of the current time.
IE. a purchase at 1:00PM would show a time purchase at 9:00PM
Previous:
New:
*20:13 -> 8:13
When viewing purchase history within the contacts page, the time is correct as well.
Unsure if being in a different timezone  will incorrectly set the time.
Manual Testing
[*Link to corresponding issue*](https://pdx-hkaus.atlassian.net/browse/TIC-139)
Win10/Chrome
=> TIC-139 Fixed Order Time

client/src/components/Ticketing/event/EventInstanceSelect.tsx, client/src/components/Ticketing/event/TicketPicker.tsx
When choosing a showing to purchase. If you were to choose a date, and then choose a time. And then select a different date, the time would already be selected and you wouldn’t be able to purchase any tickets until going back to the main page or refreshing the page
N/A
Able to go through whole process, after changing to new date and time
TIC-127
Window
=> Tic 127: Corrected issue to allow user to select new date after hitting "Choose Different Date" on Events Page

client/src/components/Ticketing/ticketingmanager/AdminPurchase/AdminPurchase.tsx
New showings would be created with a time in the format of HHmmss+00 whereas seeded events were created with a time in the format HHmmss.SSS+00. This caused problems to some recent enhancements to how dates were handled in admin purchase. This was fixed.
Also allowed admins to purchase tickets from non-active events and sorting descending by eventid.
None
Tested with new and old events
Windows 11
=> [TIC-109] Hotfix to allow purchase of new showings

client/src/components/Ticketing/ticketingmanager/Season/components/SeasonInfo.tsx, client/src/components/Ticketing/ticketingmanager/Season/components/utils/ViewSeasonInfo.tsx
Added an indicator to the SeasonInfo page that displays when a season is inactive, yet some of the events within that season are active. The indicator would not appear for active seasons or fully inactive seasons.
**This example has all but 1 event active:**
I'm not too sure that the tooltip makes enough sense so I could use some feedback on the verbiage.
None
Visual testing
[TIC-143](https://pdx-hkaus.atlassian.net/browse/TIC-143)
Windows 11
[TIC-143]: https://pdx-hkaus.atlassian.net/browse/TIC-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [TIC-143] Added Some Active Events in Season Indicator

gcp/scripts/test-client.sh
- Exports the `CI` variable for containers running E2E tests on GCP
Running with the now-default four workers slows down our tests enough to cause some of them to fail. This change sets the `CI` variable to `true` within our Playwright containers on GCP, which takes the number of workers down to two. The tests which were failing previously are now passing again.
- Changes a few other settings like timeouts and retries, but these should already be configured with deployment in mind.
- Before:
- After:
- Note that the `check stripe purchase` test has other unresolved issues right now.
- Build log:
- https://console.cloud.google.com/cloud-build/builds;region=us-west2/f212d342-dc14-44ea-97ec-53ab6d26c0c7?project=wondertix-app
- [*DEP-109: reduce number of workers running …
=> DEP-109: reduce workers used by E2E tests

.env.dist, cloudbuild.yaml, docker-compose.yml, gcp/scripts/deploy-server.sh, server/cloudbuild.yaml, server/prisma/seed.ts, server/prisma/yaml-seeder-data/tickettype.yaml
Adds a `SHOULD_SEED` environment variable so that the database is only seeded with essential data on startup if it's set to `true`. The essential data being two ticketTypes that are each expected to have specific id values in other places in code, so those two types have to be specifically seeded (the altered sequence for the id value can be found at the end of the first db migration), as well as all the `date` table values 
The goal of this is to have staging and production environments that aren't filled with test data every time code's promoted 
Created the secret in gcp with versions for each env [here](https://console.cloud.google.com/security/secret-manager/secret/SHOULD_SEED/versions?project=wondertix-app)
May have missed some environment variable configuration in some place(s)
DB …
=> Conditionally seed database 

README.md, cloudbuild.yaml
- Adds `SHOULD_SEED` environment variable to `deploy-test-server` step of main workflow.
- Updates `README.md`: removes outdated reference to `/gcbrun` and adds brief overview of CI/CD.
- None worth noting.
- Build log: https://console.cloud.google.com/cloud-build/builds;region=us-west2/63cb844f-7c10-4359-81f9-801cc154b81a?project=wondertix-app
- Following up on this: https://github.com/WonderTix/WonderTix/pull/528#issuecomment-1862151673
- Ubuntu 22.04
=> DEP-110: add conditional seeding for test server

client/package-lock.json, client/package.json
_Note: this PR reverts a part of the changes from https://github.com/WonderTix/WonderTix/pull/617_
Due to the build process that we currently use, `react-scripts` must be labeled as a `dependency` within `client/package.json`. Currently the build process runs a `npm install --omit=dev` so that the build process can be quick. This means that `react-scripts` must be considered a normal dependency to run `npm build` when a production binary is created.
Fortunately, it looks like all of the "vulnerabilities" that `npm audit` displays for `react-scripts` are false alarms, and when `npm build` is run, it is doubtful that the package would even be included since it isn't used anywhere in the react code -- just in the build process.
In short, these vulnerabilities shouldn't be a problem, and …
=> Put react-scripts back into dependencies

client/src/components/Ticketing/ticketingmanager/Event/components/EventGeneralForm.tsx, client/src/components/Ticketing/ticketingmanager/Event/components/EventGeneralView.tsx
Image is resized according to screen size like described in #443.
May want to set another max width or height.
Manually tested
Issue #443 
Windows 11 22H2 (23631.3296)
=> [WT-443] Ticketing - Resize image in Admin Events and Admin Season Page properly

client/src/components/Ticketing/event/TicketPicker.tsx, client/src/components/Ticketing/ticketingmanager/ticketingSlice.spec.ts, client/src/components/Ticketing/ticketingmanager/ticketingSlice.ts
Update ticketing state to prevent customers from adding more tickets to their cart than there are available seats for a showing by selecting different ticket types.
Note: When merged with the PR for issue 640 if a customer has added the maximum number of tickets available for a showing to their cart the showing wont show up as sold out, but rather the customer will just not be able to add additional tickets.
Implementation logic could be incorrect. 
Manual testing
#665 
M1 Mac
=> [WT-665] Update ticketing state to maintain accurate available seat count

client/src/components/Ticketing/Icons.tsx, client/src/components/Ticketing/mainpage/Navbar.tsx, client/src/components/Ticketing/ticketingmanager/RefundOrders/RefundOrders.tsx, server/src/controllers/orderController.ts
Added the ability to search by name to the Refunds page. It works like below:
1. If there are no spaces in-between words in the search query, the API returns all results where the email, first name, or last name contain the query
2. If there are spaces in the search query, the API returns all results where the first name contains the first word and the last name contains the second word (any other words are ignored)
**Other changes:**
* Orders in refunds page are sorted from newest to oldest
* Made minor improvements to the refunds interface to make the search bar more consistent with other element, and include the emails in the displayed data (now utilizing native HTML `table` to auto-size the columns).
* Entering empty string in search bar clears results rather than displayed error msg …
=> [WT-541] Added Search by Name to Refunds Page
